kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: userb-editor
  namespace: rbac-test
subjects:
  - kind: User
    name: [USER_B_EMAIL] # UserB의 이메일 주소로 변경
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
