apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: VARIABLE_DEMO
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: game.difficulty          
