kind: Pod
apiVersion: v1
metadata:
  name: pvc-mount-pod
spec:
  containers:
    - name: frontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: pvc-mount-volume
  volumes:
    - name: pvc-mount-volume
      persistentVolumeClaim:
        claimName: hello-pvc-disk
